stages:
- template: stages/deploy.yml  # Template references stage
  parameters:
    stageName: 'dev'
    jobName: 'deployDev'
    pool:
      vmImage: 'ubuntu-16.04'
    env: 'smarthotel-dev'

- stage: QA
  jobs:
  - template: jobs/deploy.yml  # Template references job
    parameters:
      name: 'DeployQA'
      pool:
        vmImage: 'ubuntu-16.04'
      env: 'smarthotel-qa'
  - job:
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - template: steps/deploy.yml # Template references step

- stage: Prod
  jobs:
  - deployment:
    displayName: 'deploy to Prod'
    environment: 'smarthotel-prod'
    variables:
    - template: variables/deploy.yml  # Template references variables
    pool:
      vmImage: ${{ variables.vmImage }}
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo ${{ variables.arch }} ${{ variables.config }}
