name: 'helloworld'
schedules:
- cron: "0 12 * * 0"
  displayName: Weekly Sunday build
  branches:
    include:
    - releases/*
  always: true

trigger:
  batch: true
  paths:
    include:
    - master/*
    - k8s/helm/partsunlimited-api

variables:
- name: envName
  value: 'smarthotel-qa'
  
stages:
- template: stages/deploy.yml  # Template references stage
  parameters:
    stageName: 'dev'
    jobName: 'deployDev'
    pool:
      vmImage: 'ubuntu-16.04'
    env: 'fromGitHub'

- stage: QA
  jobs: 
  - template: jobs/deploy.yml  # Template references job
    parameters:
      name: 'DeployQA'
      pool:
        vmImage: 'ubuntu-16.04'
      env: $(envName)
  - job:
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - template: steps/deploy.yml # Template references step

- stage: Prod
  jobs:
  - job: A
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: echo job A $(Build.Repository.Name)
  - deployment:
    displayName: 'deploy to Prod'
    environment: 'fromGitHub-2'
    dependsOn: A
    continueOnError: true
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    variables:
    - template: variables/deploy.yml  # Template references variables
    pool:
      vmImage: ${{ variables.vmImage }}
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo ${{ variables.arch }} ${{ variables.config }}
