stages:
- template: stages/deploy.yml  # Template references stage
  parameters:
    stageName: 'dev'
    jobName: 'jobA'
    pool:
      vmImage: 'ubuntu-16.04'
    env: 'smarthotel-dev'

- stage: QA
  jobs:
  - template: jobs/deploy.yml  # Template references job
    parameters:
      name: 'Windows'
      pool:
        vmImage: 'ubuntu-16.04'
      env: 'smarthotel-qa'
