stages:
- template: stages/Deploy.yml  # Template references stage
  parameters:
    stageName: 'dev'
    jobName: 'deployDev'
    pool:
      vmImage: 'ubuntu-16.04'
    env: 'smarthotel-dev'

- stage: QA
  jobs:
  - template: jobs/deploy.yml  # Template references job
    parameters:
      name: 'DeployQA'
      pool:
        vmImage: 'ubuntu-16.04'
      env: 'smarthotel-qa'

- template: stages/deploy.yml  # Template references stage
  parameters:
    stageName: 'staging'
    jobName: 'deployStaging'
    pool:
      vmImage: 'ubuntu-16.04'
    env: 'smarthotel-uat'
