variables:
- name: envName
  value: '$(Build.DefinitionName)-prod'
  
stages:
- template: stages/deploy.yml  # Template references stage
  parameters:
    stageName: 'dev'
    jobName: 'deployDev'
    pool:
      vmImage: 'ubuntu-16.04'
    env: 'smarthotel-dev'

- stage: QA
  jobs:
  - template: jobs/deploy.yml  # Template references job
    parameters:
      name: 'DeployQA'
      pool:
        vmImage: 'ubuntu-16.04'
      env: 'smarthotel-qa'
  - job:
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - template: steps/deploy.yml # Template references step

- stage: Prod
  jobs:
  - job: A
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: echo job A $(Build.Repository.Name)
  - deployment:
    displayName: 'deploy to Prod'
    environment: '$(envName)-postFix'
    dependsOn: A
    continueOnError: true
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    variables:
    - template: variables/deploy.yml  # Template references variables
    pool:
      vmImage: ${{ variables.vmImage }}
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo ${{ variables.arch }} ${{ variables.config }}
