parameters:
  name: ''
  pool: ''
  env: ''

jobs:
- deployment: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  environment: ${{ parameters.env }}
  strategy:
    runOnce:
      deploy:     
        steps:
          - script: echo 'hello'
