parameters:
  name: ''
  pool: ''
  env: ''
  sub: ''

jobs:
- deployment: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  continueOnError: true
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  variables:
    JOB_VAR: 'a job var' 
  environment: ${{ parameters.env }}
  strategy:
    runOnce:
      deploy:     
        steps:
          - script: echo $(JOB_VAR)
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: $(azureSub)
              ScriptType: 'InlineScript'
              Inline: |
                
                (Get-Module -ListAvailable | Where-Object{ $_.Name -eq 'Azure' }) ` | Select Version, Name, Author, PowerShellVersion  | Format-List;







